input.onButtonPressed(Button.A, function () {
    music.play(music.tonePlayable(370, music.beat(BeatFraction.Half)), music.PlaybackMode.UntilDone)
    music.play(music.tonePlayable(415, music.beat(BeatFraction.Quarter)), music.PlaybackMode.UntilDone)
    music.play(music.tonePlayable(466, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.play(music.tonePlayable(392, music.beat(BeatFraction.Double)), music.PlaybackMode.UntilDone)
    basic.pause(100)
    music.play(music.tonePlayable(440, music.beat(BeatFraction.Breve)), music.PlaybackMode.UntilDone)
    basic.pause(1000)
    music.play(music.tonePlayable(185, music.beat(BeatFraction.Half)), music.PlaybackMode.UntilDone)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Quarter)), music.PlaybackMode.UntilDone)
    music.play(music.tonePlayable(233, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Double)), music.PlaybackMode.UntilDone)
    basic.pause(100)
    music.play(music.tonePlayable(220, music.beat(BeatFraction.Breve)), music.PlaybackMode.UntilDone)
})
basic.showIcon(IconNames.EighthNote)
music.setTempo(500)
